### PR TITLE
COL-536, developer docs (and related scripts) need to be consistent and easy to find 

### PR DESCRIPTION
**Pull request by johncrossman**
A dev's workstation should have Apache DOC_ROOT set to `~/Projects/collabosphere/public`. Therefore, this script should neither copy static files nor require env variable DOCUMENT_ROOT.

### CODE REVIEW

**Comment by paulkerschen** [comment]
@johncrossman This makes sense. Do we have / should we have documentation about the recommended Apache DOC_ROOT setting?

**Comment by johncrossman** [comment]
@paulkerschen Yes, we should. Do not merge until I document or find such doc.

**Comment by johncrossman** [comment]
I've updated the README.md with links to files under `docs/`, renamed PDF to remove space and rebranded to SuiteC, where necessary. cc: @paulkerschen

**Comment by johncrossman** [comment]
Fyi, you can see the README rendered at https://github.com/johncrossman/collabosphere/tree/NOJIRA_install-locally

**Comment by paulkerschen** [comment]
Thanks @johncrossman, looks good.

**Pull request merged**
