### PR TITLE
COL-46 - Implement base asset library UI

### PR DESCRIPTION
**Pull request by nicolaasmatthijs**
Implement base asset library UI
https://jira.ets.berkeley.edu/jira/browse/COL-46

Implement add link UI
https://jira.ets.berkeley.edu/jira/browse/COL-48

### CODE REVIEW

**Comment by nicolaasmatthijs** [comment]
This PR builds on top of #8, which should be reviewed and merged first

**Comment by paulkerschen** [comment]
@nicolaasmatthijs This all seems to make sense to me, Christmas trees and all, and gives a nice overview of the user and asset library models. Thanks for the ping!

**Comment by nicolaasmatthijs** [comment]
@paulkerschen : If you think this is good to go, feel free to merge.

**Comment by paulkerschen** [comment]
@nicolaasmatthijs Looks like I don't have write access to the repo.

**Comment by nicolaasmatthijs** [comment]
@paulkerschen You should now be able to merge

**Comment by nicolaasmatthijs** [comment]
@paulkerschen : It looks like you merged both #8 and #9, but #9 hadn't had any review yet.

In the interest of keeping things moving, @christianv would you be able to go through the UI changes in this PR so I can follow up in a subsequent PR?

**Comment by paulkerschen** [comment]
Oh whoops, _that's_ why I didn't have write access. @nicolaasmatthijs , let me know if you want to revert and re-merge just #8.

**Comment by christianv** [comment]
@nicolaasmatthijs first look looks good to me. Just know that I won't have that much time anymore to review the big collabosphere PRs. Hopefully @simong might be able to help a bit out as well.

**Pull request merged**
