### PR TITLE
COL-352 Fix nested form in asset reuse modal

### PR DESCRIPTION
**Pull request by paulkerschen**
https://jira.ets.berkeley.edu/jira/browse/COL-352

Note that the changes are mostly indentation.

### CODE REVIEW

**Comment by nicolaasmatthijs** [comment]
@paulkerschen : It looks like this is tripping up the validation:

screen shot 2016-06-01 at 5 14 21 pm

**Comment by nicolaasmatthijs** [comment]
Back to @paulkerschen for follow-up

**Comment by paulkerschen** [comment]
@nicolaasmatthijs, looks like the problem is specific to Firefox and can be resolved by removing the `data-ng-required`on the inputs (as well as the `$valid` check on the submit button, which presumably is no longer doing anything). 

The `ng-disabled` on the submit button is still in place and prevents submission when no assets are selected. Does that seem acceptable?

**Comment by paulkerschen** [comment]
Candidate fix pushed for the validation issue, back to @nicolaasmatthijs for review.

**Comment by nicolaasmatthijs** [comment]
Looks good. Merged.

**Pull request merged**
