### PR TITLE
COL-394 - Improve and simplify content previews

### PR DESCRIPTION
**Pull request by nicolaasmatthijs**
https://jira.ets.berkeley.edu/jira/browse/COL-394

### CODE REVIEW

**Comment by johncrossman** [comment]
@nicolaasmatthijs in `node_modules/col-assets/lib/api.js` you have:
```
+  request.post(config.get('previews.url'), params, function(err, response, body) {
+    if (err) {
+      log.error({'err': err, 'asset': asset.id}, 'An error occurred when generating previews');
+      updateAssetPreview(asset, {'previewStatus': 'error'});
+      return callback({'code': 500, 'msg': 'Failed to contact the previews service'});
+    } else if (response.statusCode !== 200) {
+      log.error({'err': err, 'asset': asset.id}, 'An error occurred when generating previews');
+      updateAssetPreview(asset, {'previewStatus': 'error'});
+      return callback({'code': 500, 'msg': 'The previews service returned an error'});
     }
```
Shall we add *response.statusCode* to the `log.error()` statements above?

**Comment by johncrossman** [comment]
@nicolaasmatthijs I see `embdr` still referenced in:
* bower.json
* config/default.json
* config/test.js

Do those need update, too?

**Comment by nicolaasmatthijs** [comment]
@johncrossman : Yes, I'll fix those up

**Comment by johncrossman** [comment]
@nicolaasmatthijs  PR looks good; a couple questions posted. I'll merge if / when conflicts are resolved.

**Comment by nicolaasmatthijs** [comment]
Followed up and merged

**Pull request closed without merging**
